services:
  gazebo:
    build:
      context: ..
      dockerfile: docker/gazebo/Dockerfile
    container_name: ros2_gazebo_runtime
    network_mode: host
    ipc: host
    pid: host

    #command: bash -c "source /opt/ros/humble/setup.bash && ros2 launch gazebo_ros gazebo.launch.py"
    command: bash -c "source /opt/ros/humble/setup.bash && ros2 launch gazebo_ros gazebo.launch.py world:=/workspace/src/gazebo_maps/map_1_k.world"
    environment:
      - DISPLAY=${DISPLAY}
      - ROS_DOMAIN_ID=42
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=/tmp/.docker.xauth
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ../workspace:/workspace:rw
      - ${XCOMPOSE_AUTH:-/tmp/.docker.xauth}:/tmp/.docker.xauth:rw
    devices:
      - /dev/dri:/dev/dri
    tty: true

  navigation:
    build:
      context: ..
      dockerfile: docker/navigation/Dockerfile
    container_name: ros2_navigation_runtime
    network_mode: host
    ipc: host
    pid: host
    environment:
      - DISPLAY=${DISPLAY}
      - ROS_DOMAIN_ID=42
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ../workspace:/workspace:rw
    tty: true
    command: /bin/bash